### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by pitAlex** [phonegap/phonegap-plugin-contentsync#170]
Hello,

One of our users keeps getting a crash on the android app with the following message:

java.lang.NullPointerException: Attempt to get length of null array
	at com.adobe.phonegap.contentsync.Sync.removeFolder(Sync.java:1123)
	at com.adobe.phonegap.contentsync.Sync.removeFolder(Sync.java:1124)
	at com.adobe.phonegap.contentsync.Sync.removeFolder(Sync.java:1124)
	at com.adobe.phonegap.contentsync.Sync.removeFolder(Sync.java:1124)
	at com.adobe.phonegap.contentsync.Sync.access$1200(Sync.java:70)
	at com.adobe.phonegap.contentsync.Sync$4.run(Sync.java:522)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

The device is a Galaxy S4 (jfltevzw) on Android 5.0.

Any idea what could be the cause?

**Comment by macdonst** [comment]
@pitAlex what version of the plugin are you using in your app?

**Comment by pitAlex** [comment]
1.3.3

**Comment by ramboz** [comment]
Should be fixed by the following PR: #171

**Comment by macdonst** [comment]
Thanks @ramboz, I already merged your PR. I'll look at releasing a 1.3.4 shortly.

**Comment by macdonst** [comment]
Fixed in 1.3.4.
